# -*- coding: utf-8 -*-
"""Task 2 unemployment analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oOqKKIM4NehDYGLm4LQASrHheDdC484V

Name - Ankit Yadav

 Oasis infobyte Task 2 - Unemployment Analysis
"""

import numpy as np
import pandas as pd
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt

details= pd.read_csv('//content/Unemployment_Rate_upto_11_2020.csv')
print(details)

details.isnull().sum()

plt.figure(figsize=(12,6))
sns.heatmap(details.corr())
plt.show()

plt.figure(figsize=(20,10))
plt.title('Approximation of employment')
sns.histplot(x = details [" Estimated Employed"], hue = 'Region', data = details)
plt.show()

plt.figure(figsize=(20, 10))
plt.title("Indian Unemployment")
sns.histplot(x=" Estimated Unemployment Rate (%)", hue="Region", data=details)
plt.show()

color = sns.color_palette()
count = details ["Region"].value_counts()

plt.figure(figsize=(20,10))
sns.barplot(x = count.index, y = count.values, alpha=0.8, color=color[1])
plt.ylabel('Number of Occurrences', fontsize=12)
plt.xlabel('States', fontsize=12)
plt.title('Count the states', fontsize=15)
plt.xticks(rotation='vertical')
plt.show()

grouped_details = details.groupby(["Region"])[" Estimated Unemployment Rate (%)"].aggregate("mean").reset_index()

plt.figure(figsize=(12,8))
sns.pointplot(x = grouped_details['Region'].values, y = grouped_details[' Estimated Unemployment Rate (%)'].values, color=color[2])
plt.ylabel('Mean rate', fontsize=12)
plt.xlabel('States', fontsize=12)
plt.title("Average of mean", fontsize=15)
plt.xticks(rotation='vertical')
plt.show()

unemploment = details [["Region","Region.1", " Estimated Unemployment Rate (%)"]]
figure = px.sunburst(unemploment, path=["Region.1", "Region"],
                     values=" Estimated Unemployment Rate (%)",
                     width=700, height=700, color_continuous_scale="RdY1Gn",
                     title="Unemployment Rate in India")
figure.show()

details ["Region"].nunique()

total = details.pivot_table(" Estimated Unemployment Rate (%)",index=['Region'],aggfunc='mean')
topstate=total.sort_values(by=' Estimated Unemployment Rate (%)',ascending=False)[:27]
print(topstate)

"""# New Section"""